### ISSUE TITLE
Не работает, нужно сменить параметр base_url

### ISSUE THREAD

**Issue by bugavka** [mavrikkk/ha_routes#6]
Logger: homeassistant.setup
Source: custom_components/route/__init__.py:51
Integration: route (documentation)
First occurred: 16:23:41 (1 occurrences)
Last logged: 16:23:41

Error during setup of component route
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/home/homeassistant/.homeassistant/custom_components/route/__init__.py", line 51, in async_setup
    "haddr": config["http"]["base_url"],
KeyError: 'base_url'

Залез в __init__.py заменил на: 
    myconfig = {
        "mindst": config[DOMAIN][CONF_MIN_DST],
        "numofd": config[DOMAIN][CONF_NUMBER_OF_DAYS],
        "tz": config[DOMAIN][CONF_TIME_ZONE],
        "token": config[DOMAIN][CONF_TOKEN],
        "devs": config[DOMAIN][CONF_DEVICES],
        "haddr": **"https://мойадрес"**,
    }

и заработало. Насколько понял base_url - устарело

**Comment by mavrikkk** [comment]
добавил параметр haddr в настройки
